global:
  debug: true
  cfg_transform: configs/semantic/transform.yaml
  save_dir: runs
  device: cuda:0
  use_fp16: true
  pretrained: null
  resume: null
trainer:
  name: SegmentationTrainer
  args:
    num_iterations: 50000
    total_accumulate_steps: null
    clip_grad: 10.0
    print_interval: 20
    save_interval: 1000
    evaluate_interval: 1
    visualize_when_val: true
model:
  name: BaseSegModel
  args:
    name: unetplusplus
    encoder_name: efficientnet-b0
loss:
  name: MultiLoss
  args:
    weights: null
    losses:
      - name: CELoss
        args: {}
      - name: DiceLoss
        args: {}
metrics:
- name: PixelAccuracy
  args:
    ignore_index: 0
- name: DiceScore
  args:
    ignore_index: 0
optimizer:
  name: AdamW
  args:
    lr: 0.001
    weight_decay: 0.0005
    betas:
    - 0.937
    - 0.999
scheduler:
  name: SchedulerWrapper
  args:
    scheduler_name: cosine2
    t_initial: 7
    t_mul: 0.9
    eta_mul: 0.9
    eta_min: 1.0e-06
data:
  dataset:
    train:
      name: CSVDatasetWithMosaic
      args:
        image_dir: data/images/train
        mask_dir: data/masks/train
        csv_path: data/train.csv
        txt_classnames: configs/semantic/classes.txt
        mosaic_size: 960 
        mosaic_prob: 0.4
    val:
      name: CSVDataset
      args:
        image_dir: data/images/val
        mask_dir: data/masks/val
        csv_path: data/val.csv
        txt_classnames: configs/semantic/classes.txt
  dataloader:
    train:
      name: DataLoaderWithCollator
      args:
        batch_size: 8
        drop_last: false
        shuffle: true
    val:
      name: DataLoaderWithCollator
      args:
        batch_size: 8
        drop_last: false
        shuffle: true
