global:
  exp_name: null
  exist_ok: false
  debug: true
  cfg_transform: configs/semantic/transform.yaml
  save_dir: runs
  device: cuda:0
  pretrained: null
  resume: null
trainer:
  name: SupervisedTrainer
  args:
    num_iterations: 10000
    clip_grad: 10.0
    evaluate_interval: 1
    print_interval: 20
    save_interval: 1000
    use_fp16: true
callbacks:
  - name: LoggerCallbacks
    args: null
  - name: CheckpointCallbacks
    args:
      best_key: dice
  - name: SemanticVisualizerCallbacks
    args: null
model:
  name: BaseSegModel
  args:
    model_name: unetplusplus
    encoder_name: efficientnet-b0
loss:
  name: MultiLoss
  args:
    weights: null
    losses:
      - name: SemanticCELoss
        args: {}
      - name: DiceLoss
        args: {}
metrics:
  - name: PixelAccuracy
    args:
      ignore_index: 0
      thresh: 0.5
  - name: DiceScore
    args:
      ignore_index: 0
      thresh: 0.5
optimizer:
  name: AdamW
  args:
    lr: 0.001
    weight_decay: 0.0005
    betas:
      - 0.937
      - 0.999
scheduler:
  name: SchedulerWrapper
  args:
    scheduler_name: cosine2
    t_initial: 7
    t_mul: 0.9
    eta_mul: 0.9
    eta_min: 1.0e-06
data:
  dataset:
    train:
      name: SemanticCSVDataset
      args:
        image_dir: samples/carvana-masking/images
        mask_dir: samples/carvana-masking/masks
        csv_path: samples/carvana-masking/train.csv
        txt_classnames: samples/carvana-masking/classnames.txt
    val:
      name: SemanticCSVDataset
      args:
        image_dir: samples/carvana-masking/images
        mask_dir: samples/carvana-masking/masks
        csv_path: samples/carvana-masking/val.csv
        txt_classnames: samples/carvana-masking/classnames.txt
  dataloader:
    train:
      name: DataLoaderWithCollator
      args:
        batch_size: 32
        drop_last: false
        shuffle: true
        # collate_fn:
        #   name: MosaicCollator
        #   args:
        #     scale_range: [0.3, 0.7]
        #     p: 0.3
    val:
      name: DataLoaderWithCollator
      args:
        batch_size: 32
        drop_last: false
        shuffle: true
