train:
  name: AlbCompose
  args:
    transforms:
      - name: AlbResize
        args:
          width: 256
          height: 256
      - name: AlbNormalize
        args:
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
      - name: AlbToTensorV2
val:
  name: AlbCompose
  args:
    transforms:
      - name: AlbResize
        args:
          width: 256
          height: 256
      - name: AlbNormalize
        args:
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
      - name: AlbToTensorV2