global:
  debug: False
  cfg_transform: configs/sample/transform.yaml
  save_dir: runs
  device: cuda:0
  resume: null
  

trainer:
  name: ClassificationTrainer
  args:
    num_epochs: 100
    total_accumulate_steps: null
    clip_grad:  10.0
    print_per_iter: 100
    evaluate_per_epoch :  1
    visualize_when_val :  True


model:
  name: BaseTimmModel
  args:
    name: convnext_small
    from_pretrained: True
    num_classes: 5


loss:
  name: SmoothCELoss
  args:


optimizer:
  name: Adam
  args:
    lr: 0.001


metrics:
  - name: Accuracy
    args:
  - name: BalancedAccuracyMetric
    args: 
      num_classes: 41
  - name: F1ScoreMetric
    args:
      average: weighted
  # - name: ConfusionMatrix
  #   args:
  #     classes_map: 
      
scheduler:
  name: SchedulerWrapper
  args:
    scheduler_name: cosine2

data: # instruction here
  dataset:
    train:
      name: CSVDataset
      args:
        image_dir: "data/mapdasCLF_5cls/images/train"
        csv_path: "data/mapdasCLF_5cls/annotations/hierachies/mapdas_5cls_I_train.csv"
        txt_classnames: "configs/sample/classes.txt"
        test: False
    
    val:
      name: CSVDataset
      args:
        image_dir: "data/mapdasCLF_5cls/images/val"
        csv_path: "data/mapdasCLF_5cls/annotations/hierachies/mapdas_5cls_I_val.csv"
        txt_classnames: "configs/sample/classes.txt"
        test: True

  dataloader:
    train:
      name: CSVLoader
      args:
        batch_size: 128
        train: True
    val:
      name: CSVLoader
      args:
        batch_size: 128
        train: False
