global:
  debug: True
  cfg_transform: configs/sample/transform.yaml
  save_dir: runs
  device: cuda:0
  resume: null
  

trainer:
  name: ClassificationTrainer
  args:
    num_epochs: 100
    total_accumulate_steps: null
    clip_grad:  10.0
    print_per_iter: 2
    save_per_iter: 1000
    evaluate_per_epoch :  1
    visualize_when_val :  True


model:
  name: BaseTimmModel
  args:
    name: convnext_small
    from_pretrained: True
    num_classes: 5


loss:
  name: SmoothCELoss
  args:
    smoothing: 0.1

metrics:
  - name: Accuracy
    args:
  - name: BalancedAccuracyMetric
    args: 
      num_classes: 5
  - name: F1ScoreMetric
    args:
      average: weighted
  # - name: ConfusionMatrix
  #   args:
  #     classes_map: 

optimizer:
  name: AdamW
  args:
    lr: 0.001               # [adam: 1e-3 | sgd: 1e-2]
    weight_decay: 0.0005
    betas: [0.937, 0.999]

scheduler:
  name: SchedulerWrapper
  args:
    scheduler_name: cosine2
    t_initial: 7
    t_mul: 0.9
    eta_mul: 0.9
    eta_min: 0.000001


data: 
  dataset:
    train:
      name: CSVDataset
      args:
        image_dir: "data/mapdasCLF_5cls/images/train"
        csv_path: "data/mapdasCLF_5cls/annotations/hierachies/mapdas_5cls_I_train.csv"
        txt_classnames: "configs/sample/classes.txt"
        test: False
    
    val:
      name: CSVDataset
      args:
        image_dir: "data/mapdasCLF_5cls/images/val"
        csv_path: "data/mapdasCLF_5cls/annotations/hierachies/mapdas_5cls_I_val.csv"
        txt_classnames: "configs/sample/classes.txt"
        test: True

  dataloader:
    train:
      name: CSVLoader
      args:
        batch_size: 64
        train: True
    val:
      name: CSVLoader
      args:
        batch_size: 64
        train: False
