global:
  exp_name: null
  exist_ok: false
  debug: false
  cfg_transform: configs/classification/transform.yaml
  save_dir: runs
  device: cuda:0
  pretrained: null
  resume: null
trainer:
  name: SupervisedTrainer
  args:
    num_iterations: 10000
    clip_grad: 1.0
    evaluate_interval: 1
    print_interval: 100
    save_interval: 2000
    use_fp16: true
callbacks:
  - name: LoggerCallbacks
  - name: CheckpointCallbacks
    args:
      best_key: bl_acc
  - name: ClassificationVisualizerCallbacks
model:
  name: BaseTimmModel
  args:
    model_name: convnext_small
    from_pretrained: true
loss:
  name: ClassificationCELoss
metrics:
  - name: Accuracy
  - name: BalancedAccuracyMetric
  - name: F1ScoreMetric
    args:
      average: weighted
  - name: ConfusionMatrix
  - name: ErrorCases
optimizer:
  name: AdamW
  args:
    lr: 0.001
    weight_decay: 0.0005
    betas:
      - 0.937
      - 0.999
scheduler:
  name: SchedulerWrapper
  args:
    scheduler_name: cosine2
    t_initial: 7
    t_mul: 0.9
    eta_mul: 0.9
    eta_min: 1.0e-06
data:
  dataset:
    train:
      name: ClassificationImageFolderDataset
      args:
        image_dir: samples/dog-vs-cats/train
        txt_classnames: samples/dog-vs-cats/classnames.txt
    val:
      name: ClassificationImageFolderDataset
      args:
        image_dir: samples/dog-vs-cats/val
        txt_classnames: samples/dog-vs-cats/classnames.txt
  dataloader:
    train:
      name: DataLoaderWithCollator
      args:
        batch_size: 16
        drop_last: false
        shuffle: false
        collate_fn:
          name: MixupCutmixCollator
          args:
            mixup_alpha: 0.4
            cutmix_alpha: 1.0
            weight: [0.2, 0.2]
        sampler:
          name: BalanceSampler
          args:
    val:
      name: DataLoaderWithCollator
      args:
        batch_size: 16
        drop_last: false
        shuffle: true
