
# learning rate policy
lr_policy:
  name: "adam"                         #[adam|sgd]
  lr: 0.0002                            #[adam: 1e-3 | sgd: 1e-2]
  momentum: 0.937
  weight_decay: null
  test: 
    test: 0

lr_scheduler:
  name: "cosine"                      #[plateau | cosine | 1cycle-yolo | 1cycle]
                                      # if need to specify more scheduler arguments, do it here